DEBUG = True
SECRET_KEY= 'thisissecret'

GOOGLE_PLACE_KEY = 'Place your Key'

MONGO_URI = 'YOUR DB URI'

FOURSQUARE_CLIENT_ID = 'Place your key'
FOURSQUARE_CLIENT_SECRET = 'Place your key'
FOURSQUARE_VERSION = '20180323'